package com.validus.backend.domain.enums;

public enum AuditAction {
    INVOICE_CREATED,
    INVOICE_UPDATED,
    INVOICE_SUBMITTED,
    INVOICE_APPROVED_BUYER,
    INVOICE_APPROVED_BUSINESS,
    INVOICE_REJECTED,
    INVOICE_ACCOUNTED,
    INVOICE_READY_FOR_PAYMENT,
    INVOICE_PAID,
    INVOICE_CANCELLED,
    ATTACHMENT_ADDED,
    PAYMENT_BATCH_CREATED,
    PAYMENT_BATCH_SUBMITTED,
    PAYMENT_BATCH_APPROVED_AUDIT,
    PAYMENT_BATCH_APPROVED_DAF,
    PAYMENT_BATCH_REJECTED,
    PAYMENT_BATCH_EXECUTED
}
