spring.application.name=validus-backend

# SQL Server (change if needed)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=validus;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=HelloWorld2025
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.open-in-view=false

# Disable SQL init scripts (no data.sql)
spring.sql.init.mode=never

# Swagger UI at /swagger-ui.html
management.endpoints.web.exposure.include=health,info
